In [1]:
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv", header=None)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24983 entries, 0 to 24982
Columns: 101 entries, 0 to 100
dtypes: float64(100), int64(1)
memory usage: 19.3 MB


In [3]:
df.head()

0      1      2      3      4     5     6     7     8      9    ...    91   \
0   74  -7.82   8.79  -9.66  -8.16 -7.52 -8.50 -9.85  4.17  -8.98  ...   2.82   
1  100   4.08  -0.29   6.36   4.37 -2.38 -9.66 -0.73 -5.34   8.88  ...   2.82   
2   49  99.00  99.00  99.00  99.00  9.03  9.27  9.03  9.27  99.00  ...  99.00   
3   48  99.00   8.35  99.00  99.00  1.80  8.16 -2.82  6.21  99.00  ...  99.00   
4   91   8.50   4.61  -4.17  -5.39  1.36  1.60  7.04  4.61  -0.44  ...   5.19   

     92     93     94     95     96     97     98     99     100  
0  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  

[5 rows x 101 columns]

In [4]:
df.drop(0, axis=1, inplace=True)
df.head()

1      2      3      4     5     6     7     8      9      10   ...  \
0  -7.82   8.79  -9.66  -8.16 -7.52 -8.50 -9.85  4.17  -8.98  -4.76  ...   
1   4.08  -0.29   6.36   4.37 -2.38 -9.66 -0.73 -5.34   8.88   9.22  ...   
2  99.00  99.00  99.00  99.00  9.03  9.27  9.03  9.27  99.00  99.00  ...   
3  99.00   8.35  99.00  99.00  1.80  8.16 -2.82  6.21  99.00   1.84  ...   
4   8.50   4.61  -4.17  -5.39  1.36  1.60  7.04  4.61  -0.44   5.73  ...   

     91     92     93     94     95     96     97     98     99     100  
0   2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1   2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2  99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3  99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4   5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  

[5 rows x 100 columns]

In [5]:
test_set = df.replace({99: np.nan})
test_set.head()

1     2     3     4     5     6     7     8     9     10   ...   91   \
0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50 -9.85  4.17 -8.98 -4.76  ...  2.82   
1  4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  9.22  ...  2.82   
2   NaN   NaN   NaN   NaN  9.03  9.27  9.03  9.27   NaN   NaN  ...   NaN   
3   NaN  8.35   NaN   NaN  1.80  8.16 -2.82  6.21   NaN  1.84  ...   NaN   
4  8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  5.73  ...  5.19   

    92    93    94    95    96    97    98    99    100  
0   NaN   NaN   NaN   NaN   NaN -5.63   NaN   NaN   NaN  
1 -4.95 -0.29  7.86 -0.19 -2.14  3.06  0.34 -4.32  1.07  
2   NaN   NaN  9.08   NaN   NaN   NaN   NaN   NaN   NaN  
3   NaN   NaN  0.53   NaN   NaN   NaN   NaN   NaN   NaN  
4  5.58  4.27  5.19  5.73  1.55  3.11  6.55  1.80  1.60  

[5 rows x 100 columns]

In [6]:
test_set.describe(include = 'all')

1             2             3             4             5    \
count  16452.000000  18184.000000  16642.000000  15608.000000  24977.000000   
mean       0.904573      0.208460      0.316574     -1.449114      0.403556   
std        5.171798      5.597327      5.399806      5.234654      5.255700   
min       -9.950000     -9.950000     -9.950000     -9.950000     -9.950000   
25%       -2.670000     -4.420000     -4.030000     -5.870000     -3.690000   
50%        1.600000      0.830000      0.780000     -1.460000      1.120000   
75%        4.900000      4.820000      4.660000      2.520000      4.470000   
max        9.370000      9.370000      9.370000      9.370000      9.370000   

                6             7             8             9             10   \
count  20431.000000  24976.000000  24981.000000  15752.000000  20324.000000   
mean       1.594447     -0.429662     -0.624085     -0.557031      1.301231   
std        4.900540      5.495931      4.929144      5.162224      5.087359   
min       -9.950000     -9.950000     -9.950000     -9.950000     -9.950000   
25%       -1.310000     -5.290000     -4.610000     -4.760000     -2.090000   
50%        2.230000     -0.050000     -0.290000     -0.190000      1.940000   
75%        5.440000      3.880000      3.060000      3.300000      5.390000   
max        9.470000      9.610000      9.760000      9.900000      9.370000   

       ...          91           92           93            94            95   \
count  ...  9672.000000  9889.000000  9988.000000  10200.000000  10265.000000   
mean   ...     2.038527     1.179744     2.504041      1.173482      1.039130   
std    ...     5.060445     5.127291     4.611339      5.140307      5.167043   
min    ...    -9.950000    -9.950000    -9.950000     -9.950000     -9.950000   
25%    ...    -0.932500    -2.380000    -0.100000     -2.280000     -2.570000   
50%    ...     2.860000     1.800000     3.160000      1.750000      1.650000   
75%    ...     6.120000     5.290000     6.070000      5.290000      5.100000   
max    ...     9.560000     9.420000     9.370000      9.420000      9.370000   

                96            97            98            99           100  
count  10370.000000  10520.000000  10666.000000  10910.000000  9943.000000  
mean       1.528003      1.673750      0.767692     -0.031244     1.354711  
std        4.852069      5.025076      5.393833      5.176806     5.300409  
min       -9.950000     -9.950000     -9.950000     -9.950000    -9.950000  
25%       -1.347500     -1.170000     -3.400000     -4.170000    -2.330000  
50%        2.140000      2.480000      1.460000      0.290000     2.140000  
75%        5.277500      5.630000      5.150000      3.980000     5.730000  
max        9.370000      9.370000      9.370000      9.370000     9.370000  

[8 rows x 100 columns]

In [7]:
#Finding the best- and the worst-rated jokes
average = test_set.mean(axis = 0)
average.sort_values(ascending = False)

50    3.665085
89    3.574720
36    3.312500
27    3.189821
32    3.155988
        ...   
13   -1.762882
57   -1.990664
44   -2.111891
16   -3.104818
58   -3.833880
Length: 100, dtype: float64

In [8]:
arr = test_set.values # Labeling the label 10% of the dataset cells that are not NaNs as 99
print(arr.shape)  

(24983, 100)


In [9]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

2498300 (2498300,)


In [10]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(orig!= np.nan)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [11]:
new_arr, idx = replace(arr, 0.1)

In [13]:
arr[idx[0][0], idx[1][0]]

3.98

In [15]:
n_latent_factors = 2

user_ratings = df.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [16]:
latent_item_features

array([[0.08391403, 0.02684757],
       [0.58421947, 0.16304754],
       [0.0086573 , 0.94385097],
       [0.07041805, 0.65863287],
       [0.00998894, 0.27940916],
       [0.4740643 , 0.03522293],
       [0.30702496, 0.46613038],
       [0.50395731, 0.30732442],
       [0.24316038, 0.56438676],
       [0.10719441, 0.92498163],
       [0.76637729, 0.68115383],
       [0.96511464, 0.04933966],
       [0.63247563, 0.03517334],
       [0.87520777, 0.81341757],
       [0.29312833, 0.44424048],
       [0.01357366, 0.44043507],
       [0.20563685, 0.61186211],
       [0.28944515, 0.2446302 ],
       [0.47658892, 0.06233817],
       [0.80724418, 0.11514257],
       [0.93669182, 0.86463282],
       [0.17048769, 0.10070547],
       [0.85020953, 0.84235208],
       [0.41804902, 0.62670662],
       [0.63772774, 0.94191501],
       [0.4203788 , 0.41908948],
       [0.42338521, 0.00922462],
       [0.5118027 , 0.69069125],
       [0.07314443, 0.69634071],
       [0.11688636, 0.82792525],
       [0.

In [17]:
df.iloc[17273,26]

-6.84

In [19]:
df.iloc[20732, 52] #rating that user 20732 has given to joke 52

5.73

In [20]:
latent_user_preferences

array([[0.94937847, 0.54332676],
       [0.20490624, 0.17939672],
       [0.67107128, 0.50836701],
       ...,
       [0.19421522, 0.9720087 ],
       [0.59691823, 0.63518119],
       [0.48353508, 0.30253171]])

In [21]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if not np.isnan(rating) and rating != 99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [22]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[0.09425318, 0.64323347, 0.52103854, ..., 0.7907975 , 1.12936078,
        1.34760344],
       [0.02201088, 0.14896041, 0.1710977 , ..., 0.17647207, 0.27803694,
        0.34686844],
       [0.06996072, 0.4749409 , 0.48563236, ..., 0.57056836, 0.86689271,
        1.06463329],
       ...,
       [0.04239346, 0.27194794, 0.91911273, ..., 0.24203696, 0.70608099,
        1.05178488],
       [0.06714289, 0.45229598, 0.60468408, ..., 0.52458188, 0.87207967,
        1.11196429],
       [0.04869762, 0.33181766, 0.28973095, ..., 0.40517304, 0.58944363,
        0.7096232 ]])

In [ ]:
num_iter = 30
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
plt.figure()
plt.plot(np.arange(0, num_iter, 10000), hist)
plt.xlabel("Iterations")
plt.ylabel("MSE")
plt.show()

Iteration 0/30:	MSE=26.169758


In [ ]:
df_movie = pd.read_excel('movies_latent_factors.xlsx', sheet_name= 0)
df_movie.head()